---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-postgres
  namespace: immich
spec:
  encryptedData:
    password: AgCATayfwo6yfYhvFVXAFp2N0N9BLw5/1oPFXApejuKM94X0q3KxggKHVceJt7elrSshNfKuti1y/+yCUg2ELSEAUeh8GFcGZ7b3an+BgniY4iGMQEUVuEc7PfkGrnLemkVIR7YA/zIl+3+Kc/DyyUeXnrRzcwpV6FJaC5tdLQ2n+yBczEMOG8v8FJiCtwGieSC6rZwGhrV/5Mwjm+BpcyIsqFiN2blvu7PSRDQAyPkAU4O3Hc26JM5z4E2AdkoL7wfPDIB91W5UygrrA0fUKvnRygd71Z3YSG+1MNRZEtH05tuDqs2MMUk6mlbEtq/JLTRj5wH5Sd/H8tPENIINE2dJZt8iFCcUn09tkU8tHPu8K6emZXMKRtevRnEpaE37EmqTE93Iy+vHy/w4QdIxgkElByLGplMlAzfjJJswki8rL0kYNz0xY9Ucct8mxiBT5k2H8mT2iH/0w7rNwh+1Q9MtXvF2E0F+WAedu/yTGOMt4W9nt5YErLD1qMJh3+HGN/TYOGnUdpYkXu/2tO0LutIVFXK1TnfUeemky7DKsOrSeHCZNC+byJOH2T5gsXJ2UOn49lXXaPPeGVtFrOS7scB3/OwpvuuMAoeLJzeGPLgpoZHMCXBF6pVvd9dYhCXUTUpendvcqZDbBLFB1l4JZ9iP0RUj13LmXNfRyiNq809CPRYqvUwEmnLPc7nxdGtxUz3Xn6mpKMPd7+R6zfjkZFxDtbOXvg4VxJ2kmdmAsCiqBA==
  template:
    metadata:
      name: immich-postgres
      namespace: immich
