---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAE3a2zJ7oLemt8AQ4BQQWuAoawFUqY84Sk348whusnlIs5Zvpo7lBudo99NjR04J4EKjWFEkam5vetehhGXhM8hTTqXJ97UkdqWGKLoVOa0Nq72puAmSKNUnDznRQ1K7oiUfmvb0snVJiVM8nByULwMR3YhHz0pJRnsONpZNmTIBWwbALXNJT0Vymoy8cDs0JWPovfzmbJsS4kceLF4r5BGatyzMDIF2xx3nVZIo+4C8udWc809gyyx0a24ySbAMUedbIu7sGrgDoIHrphYQVOnX3SoYjxOvvnAdP2oEzD6H3LZ56qSP28CKH3CRnMdmzeGngrZ8Wlq0j033DmuB2Y9bd2w3+mWZ0VsVtFHH80K1EFA748E3rIDGPnvi6ZQnoHZkC0Jz0dwOEiIqFFqz07UWIfACiMfrtzdEf060051+p42LAYMOl1eW2dpIZpWfWiuiNl9V3aPI2VD69oyXrcxeSmHuC3fOoT9uTvnp/DOo0IdhwBtzTD2ttfTljckZ9YYXmAoRRgu0ks/J+51r92ZrcWGR1eL4t3YpGaU82S8pvznatiIwd72igKAXdXaQB2cx9Ajn+tx2yIt1LpfNid4rQEZKGyYoL1it6rN2Ridj2vWCbBS0unIl9xGKsCma6cYXltcONj1FY9rAs5CMog0uiUwgeL7nN2h/m/3rFSJBQsj1nIIROB8VkhN0jnVwJbLikTTzuyTgcTAXvVruKEBQ==
    client_secret: AgBADo++4nei/mpQhqbuMIJAB8balH8fNvbQrcvzfKRos0tp1caUthQtzZsTzL9CzbWkspJjkQECtqGGGDlvktJodjZuTNBX7ZA28jZ18eQrDYKLW2NEbXrN/utpySAmSJG7am4aE32HbFTceqyRzZucrCeCgBZ98lD25CXrcRtimfn9hlTFmnoTC5eNQEL6szYdLhDtSHnvH8plOJbAZqSt5+b8zc/z0o3NukdIPA59KgseyEmQ6xS2nnZGOJynPEDXiNW+oY/xPoolQAIph+c5W/JTUWrqnfxoL8101PhcZo3mzYByVFqXYHmAeFOWSNFHn5gY6/CSUsDDIUsNKPZJfG0ZjZrSbRDRonVbOLaSDpY3x7M+Iqkn3wHeYScKXSlHY/e22G+tllYSA8dyP0LhDtSW8m5d/UbYBLPRlVKnxLJR3mN3QyNkDs9TibviF19nfC6iv8uMTHBDS4KjlR5bU8VFwJ3x7og+7julV5MoOqk6S+9pSU5ELU1mqHVRGn6+bDq6U50l571izBsMtj+u7iG7zs21Ol/mVPakGkD35t52rWExLe6AnGTJbuRGCf4jpltcMzrBSRGrOvhgVmgTdjt6KHGq1Iy0G5TXN+3IW2BNKogv+q6SMIEESZny4VwJFzkBGHOlT5YvpbmnUS0ipxpDwgWBiwak/pajlTQULt9i67+fN7gs6TDIqVNzPjhX21ZUhdpiQw9jSmFfzuOtPg7/8ICGVluF+xIPeh+m2oURLheEEO+t8lKLzx+tuWslxzgCW0KbkxnkqjWlsZo2
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
